# Workflow for Backend
name: CI - Backend (Build Maven package -> Run JUnit test, Build Docker Image)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - Develop
      - master

jobs:
  build:
    runs-on:
      ubuntu-latest
      # Service containers to run with `runner-job`
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
          cache: maven
      - run: cd BackEnd/ && mvn install
      - name: Build LoginMicroservices and run JUnit tests
        run: cd BackEnd/loginmicroservices/ && chmod +x mvnw && ./mvnw package
      - name: Build BookMicroservices and run JUnit tests
        run: cd BackEnd/bookmicroservices/ && chmod +x mvnw && ./mvnw package
      - name: Build TransactionMicroservices and run JUnit tests
        run: cd BackEnd/transactionmicroservices/ && chmod +x mvnw && ./mvnw package
      - name: Build docker images
        id: build-images
        run: |
          # Build docker containers
          cd BackEnd/ && docker-compose build
