# Workflow for Frontend
name: CI - Frontend (ESlint -> Prettier -> UnitTest -> Build)

on:
  push:
    branches: [devops/SEPT123-ted_vu-base_devops]
  pull_request:
    branches: [Develop]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x] # use node version 12 to build FE

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: "Frontend: Install packages by npm"
        run: npm i
        working-directory: ./FrontEnd/myfirstapp

      - name: "Frontend: Build"
        run: npm run build
        working-directory: ./FrontEnd/myfirstapp

      - name: "Frontend: Run test"
        run: npm test
        working-directory: ./FrontEnd/myfirstapp

      - name: "Frontend: Checking ESlint error"
        run: npm run lint:check
        working-directory: ./FrontEnd/myfirstapp

      - name: "Frontend: Checking source code format"
        run: npm run format:check
        working-directory: ./FrontEnd/myfirstapp
