# Workflow to build backend Docker image on CI server
name: CICD - Backend (Build Docker images and Push to ECR)

on:
  push:
    branches: [Develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push the images to Amazon ECR
        id: build-deploy-images
        run: |
          # Build docker containers and push them to ECR
          cd BackEnd/ && docker-compose build
          docker push 580827140556.dkr.ecr.ap-southeast-2.amazonaws.com/bookeroo-login-dev
          docker push 580827140556.dkr.ecr.ap-southeast-2.amazonaws.com/bookeroo-book-dev
          docker push 580827140556.dkr.ecr.ap-southeast-2.amazonaws.com/bookeroo-transaction-dev
          # Force services to re-deploy using the new images
          aws ecs update-service --cluster ecs-bookeroo-dev --service bookeroo-service-login --force-new-deployment
          aws ecs update-service --cluster ecs-bookeroo-dev --service bookeroo-service-book --force-new-deployment
          aws ecs update-service --cluster ecs-bookeroo-dev --service bookeroo-service-transaction --force-new-deployment