# Workflow to build and deploy Docker image
name: CICD - Frontend(Build Docker image and push to ECR then deploy the image)

on:
  push:
    branches: [Develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_FE }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_FE }}
          aws-region: ap-southeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push the images to Amazon ECR
        id: build-deploy-images
        run: |
          # Build docker containers and push them to ECR
          cd FrontEnd/myfirstapp/ && docker build . --file Dockerfile.prod --tag 500737272218.dkr.ecr.ap-southeast-2.amazonaws.com/sept-fe:latest
          docker push 500737272218.dkr.ecr.ap-southeast-2.amazonaws.com/sept-fe:latest
          aws ecs update-service --cluster sept-bookeroo-prod --service sept-fe-prod --force-new-deployment
